### ISSUE TITLE
API Security

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#414]
- For tickets and categories, visibility of the ticket will be driven by the user's security. If they cannot see the ticket/category on the web interface, they should not be able to retrieve the ticket/category from the API.

**TODO:**
- [x] Add page for creating / resetting tokens
- Add authentication to endpoints that require authentication:
    - [x] Admin - Canned Responses
    - [x] Admin - Ticket Templates
    - [x] Admin - View Ticket (admin has some extra information such as the audit trail)
- [x] If the endpoint is trying to be accessed without a token, or if the user does not have access to the requested item, return a 404 (this is to help deter hackers trying to find valid endpoints).  If an invalid token is supplied, return a 422.
- [x] Parse the `X-Auth-Token` header to get the token for the user, and lookup the `SHA-512` hash of the token to find the user.
