### ISSUE TITLE
Roll back all Mods for HESK additions that will be part of HESK 2.6.0

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/Mods-for-HESK#88]
**branch:** remove-2-6-0-features

Need to remove the following features:

 - [x] #25: Dynamic columns on ticket dashboard
 - [x] #73: Notify customer when ticket is closed
    - May need to tweak HESK 2.6.0's implementation to allow for custom statuses.
 - [x] Maintenance mode
 - [x] Link IP address to WHOIS service
 - [x] #62: Set default customer notification option in profile
 - [x] Edit note
 - [x] Attach item to note
 - [x] #29: IP / Email bans
    - [x] Migration to move existing IP / Email bans to the HESK 2.6.0 implementation may be needed. This will be addressed in a separate issue.
